name: ${LOCAL_PROJECT_NAME}
services:
  wordpress:
    image: wordpress:${LOCAL_WP_VERSION:-latest}
    ports:
      - "${LOCAL_WP_PORT:-8080}:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${LOCAL_DB_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${LOCAL_DB_PASSWORD:-wordpress}
      - WORDPRESS_DB_NAME=${LOCAL_DB_NAME:-wordpress}
    depends_on:
      - db
    networks:
      - wp-network
  db:
    image: mysql:${LOCAL_DB_VERSION:-latest}
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${LOCAL_DB_ROOT_PASSWORD:-wordpress}
      - MYSQL_DATABASE=${LOCAL_DB_NAME:-wordpress}
      - MYSQL_USER=${LOCAL_DB_USER:-wordpress}
      - MYSQL_PASSWORD=${LOCAL_DB_PASSWORD:-wordpress}
    networks:
      - wp-network
volumes:
  db-data:
networks:
  wp-network:
    driver: bridge
